### ISSUE TITLE
Modulus crashed on duplicate email address

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#221]
We should check for duplicates before allowing people to register. See modulus logs below for details

**Comment by drenfr01** [comment]
For your convenience, below is a log dump of the servo that crashed.

    at [object Object].Meteor.methods.createNewUser (app/server/methods.js:197:20)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    - - - - -
    at Object.toError (/mnt/app/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /mnt/app/node_modules/mongodb/lib/mongodb/collection/core.js:542:27
    at /mnt/app/node_modules/mongodb/lib/mongodb/db.js:1129:7
    at /mnt/app/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/mnt/app/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /mnt/app/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/mnt/app/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/mnt/app/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/mnt/app/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
Exception while invoking method 'createNewUser' MongoError: E11000 duplicate key error index: Gy3dubiq.users.$emails.address_1  dup key: { : "zulmamorales79@gmail.com" }
    at Object.Future.wait (/mnt/app/node_modules/fibers/future.js:326:15)
    at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
    at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:634:1)
    at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:574:1)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:159:1)
    at [object Object].Meteor.methods.createNewUser (app/server/methods.js:197:20)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    - - - - -
    at Object.toError (/mnt/app/node_modules/mongodb/lib/mongodb/utils.js:110:11)
    at /mnt/app/node_modules/mongodb/lib/mongodb/collection/core.js:542:27
    at /mnt/app/node_modules/mongodb/lib/mongodb/db.js:1129:7
    at /mnt/app/node_modules/mongodb/lib/mongodb/db.js:1843:9
    at Server.Base._callHandler (/mnt/app/node_modules/mongodb/lib/mongodb/connection/base.js:445:41)
    at /mnt/app/node_modules/mongodb/lib/mongodb/connection/server.js:468:18
    at [object Object].MongoReply.parseBody (/mnt/app/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at [object Object].<anonymous> (/mnt/app/node_modules/mongodb/lib/mongodb/connection/server.js:426:20)
    at [object Object].emit (events.js:95:17)
    at [object Object].<anonymous> (/mnt/app/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
Exception while invoking method 'login' Error: Match error: Failed Match.Where validation in field username in field user.username
    at checkSubtree (packages/check/match.js:223:1)
    at packages/check/match.js:296:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at checkSubtree (packages/check/match.js:290:1)
    at check (packages/check/match.js:32:1)
    at [object Object].condition (packages/accounts-password/password_server.js:111:1)
    at checkSubtree (packages/check/match.js:220:1)
    at packages/check/match.js:293:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at checkSubtree (packages/check/match.js:290:1)
Sanitized and reported to the client as: Match failed [400]
