### ISSUE TITLE
Laura indicated that the app wasn't working at 10 am 3/4/2016

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#336]
I saw this below in the logs:

Got exception while polling query: MongoError: Runner error: Overflow sort stage buffered data usage of 33554672 bytes exceeds internal limit of 33554432 bytes

**Comment by drenfr01** [comment]
looks like the issues is that we're attempting to sort too large of a collection in mongo: http://stackoverflow.com/questions/27023622/overflow-sort-stage-buffered-data-usage-exceeds-internal-limit

the solutions appears to be adding in indices to reduce the size of the sort

@ballek

**Comment by drenfr01** [comment]
I tried to redeploy the app and hit some errors:

Error: Can't find npm module 'body-parser'. Did you forget to call 'Npm.depends' in package.js within the 'iron_router' package?
    at Object.Npm.require (/mnt/app/programs/server/boot.js:147:17)
    at assert (packages/iron:router/lib/body_parser_server.js:1:1)
    at /mnt/app/programs/server/packages/iron_router.js:1269:4
    at /mnt/app/programs/server/packages/iron_router.js:1455:3
    at /mnt/app/programs/server/boot.js:205:10
    at Array.forEach (native)
    at Function._.each._.forEach (/mnt/app/programs/server/node_modules/underscore/underscore.js:79:11)

**Comment by drenfr01** [comment]
the two errors were solved by 

1) adding an index to transactionDate for the Transactions collection
2) upgrading the project to Meteor 1.2.1 and deploying it
