### ISSUE TITLE
cannot check into older events

### ISSUE THREAD

**Issue by drenfr01** [drenfr01/unionCapital#443]
see this bug: "Exception while invoking method 'insertTransaction' TypeError: Cannot read property 'rules' of undefined
    at [object Object].insertTransaction (server/methods/transactionMethods.js:26:24)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at tryCallTwo (/mnt/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/mnt/app/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:200:13)
"

**Comment by drenfr01** [comment]
@ballek well color me stupid, but I do not remember this bug from a year ago. Have you seen it occur / heard any member's complain?

**Comment by ballek** [comment]
@drenfr01 i reckon i don't remember what this is about either! i see people check into past events frequently, it's a little feature that some members have definitely figured out :)
